# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Configure AWS Credentials Action for Github
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

      - name: SAM Validate
        run: sam validate

      - name: Replace secrets in code
        run: |
          sed -i -e 's/TWITTER_API_KEY_SECRET/${{ secrets.TWITTER_API_KEY }}/g' \
          -e 's/TWITTER_SECRET_KEY_SECRET/${{ secrets.TWITTER_SECRET_KEY }}/g' \
          -e 's/TWITTER_ACCESS_TOKEN_SECRET/${{ secrets.TWITTER_ACCESS_TOKEN }}/g' \
          -e 's/TWITTER_TOKEN_SECRET_SECRET/${{ secrets.TWITTER_TOKEN_SECRET }}/g' \
          -e 's/SPOTIFY_AUTHORIZATION_SECRET/${{ secrets.SPOTIFY_AUTHORIZATION }}/g' secrets.py

      - name: SAM build
        run: sam build

      - name: SAM Deploy
        run: |
          sam deploy --stack-name missing-jre-stack \
            --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1t1v62pr4x2og \
            --capabilities CAPABILITY_IAM
